### ISSUE TITLE
have a error!

### ISSUE THREAD

**Issue by mimosz** [tomash/easy_globalize2_accessors#1]
undefined local variable or method `globalize_options'

gems/globalize2-0.2.1/lib/globalize/active_record.rb:119:in `method_missing'

**Comment by mimosz** [comment]
/gems/globalize2-0.2.1/lib/globalize/active_record.rb:119:in `method_missing'
/vendor/plugins/easy_globalize2_accessors/lib/active_record/globalize_accessors.rb:10:in`globalize_accessors'

**Comment by tomash** [comment]
will try to reproduce it. maybe sven broke some api compatibility in globalize2 yet again.

does your model have "vanilla globalize2" translates macro invocation BEFORE the globalize_accessors?

**Comment by ironoxid** [comment]
I've this problem but it's releated to a wrong install url in project's home!
uninstall plugin
script/plugin remove easy_globalize2_accessors
and install from right url
script/plugin install git://github.com/tomash/easy_globalize2_accessors.git

**Comment by tomash** [comment]
wow, so somebody is actually using it (besides me and astropanic).

I've corrected the README, sorry for this dumb mistake guys! (that's when you pull without checking changes in README)

**Comment by tomash** [comment]
so, mimosa, I've closed the issue -- but if it doesn't solve your problem, feel free to reopen!
