### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by ironoxid** [tomash/easy_globalize2_accessors#2]
can you fix install link in project's home page?
Actually it binds to script/plugin install git://github.com/astropanic/easy_globalize2_accessors.git. It seems to be an outdated version. It doesn't work and someone can open issues on your version and waste your time ;)
Thank you!
Regards
Giulio

**Comment by tomash** [comment]
Done, thanks for pointing that out!

**Comment by ironoxid** [comment]
Thank you for this plugin! It's amazing to fast port old globalize1 apps to globalize2 :) 
It should be on globalize2 migration link list!
