### ISSUE TITLE
Globalize3

### ISSUE THREAD

**Issue by marzdrel** [tomash/easy_globalize2_accessors#3]
Any idea what changed in globalize3, that broke this code? At this moment every accessor updates current active language version, not specific one...

**Comment by marzdrel** [comment]
Actually just removing the self-assign line fixes the problem for gobalize3:

```
self[attr_name] = val
```

Any idea why this line is even there?

**Comment by tomash** [comment]
I have no idea, we should ask svenfuchs. I'll have a look at it during the upcoming weekend :)

**Comment by marzdrel** [comment]
I am doing some active developement at this point, and after this line was removed accessors works as a charm. With that line included Globalize updates the selected language (ex. name_es) AND the language currelntly set as default (if those two are different). :-)

**Comment by tomash** [comment]
so how about a fork, commit and pull request? :)

**Comment by marzdrel** [comment]
Do you really think it makes sense, since all that needs to be done is removal of one line?
