### ISSUE TITLE
Disable fallback for editing (for accessors only)

### ISSUE THREAD

**Issue by marzdrel** [tomash/easy_globalize2_accessors#4]
Hi,

This is not strict issue report, more of a question about use case. is there any neat way to disable I18n fallback for editing? The problem is, that accessors aren't that usable if fallback is enabled. Accessing title_es in the form result in title_en beeing returned if the translation is not yet available. 

Do you have any suggestion how to modify this? Or how to fix the plugin to ignore fallback while accessing the fields?

**Comment by tomash** [comment]
Hi,

I'm using I18n fallbacks with globalize and consider it a bliss. However it would be nice to have a extra method for globalized field like #fallback? set to true whenever the value is not the actual one, but the fallback.

However I don't know how much hacking would that require, but I'll have a look at it.

**Comment by marzdrel** [comment]
Well, imagine you have some sort of an admin page, where you can edit say 5 different language versions of every piece of text. Now, if you don't already have any translation, then in the form all the versions will get populated with default fallback one.

If you only want to edit one of those versions, you have to clear the rest out. If you don't - the translations will get populated into wrong versions resulting in total mess.

In general, if I want to edit the language versions I need the translation returned without fallback, otherwise it becomes a nightmare.

Of course I need this only for edition. I do want fallbacks in the app while displaying the texts on the pages of course. 

Do you have any tips on how to solve that riddle?

**Comment by tomash** [comment]
Like I wrote above -- having a #fallback flag would help. I'll see if it's possible.
